/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type LanguageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "language";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type PublisherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publisher";
};

export type Bibliography = {
  _id: string;
  _type: "bibliography";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  cover?: ImageWithMetadata;
  languages?: Array<
    {
      _key: string;
    } & LanguageReference
  >;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  publisher: PublisherReference;
  tagSelector?: TagSelector;
  affiliateLink?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type TagSelector = {
  _type: "tagSelector";
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithMetadata = {
  _type: "imageWithMetadata";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  alt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type WebSource = {
  _id: string;
  _type: "webSource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  cover?: ImageWithMetadata;
  category: CategoryReference;
  tagSelector?: TagSelector;
  affiliateLink?: string;
};

export type Publisher = {
  _id: string;
  _type: "publisher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Glossary = {
  _id: string;
  _type: "glossary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  image?: ImageWithMetadata;
};

export type Bookshop = {
  _id: string;
  _type: "bookshop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagSelector?: TagSelector;
  location: Location;
  address?: string;
  socialLinks?: SocialLinks;
};

export type SocialLinks = {
  _type: "socialLinks";
  links?: Array<{
    platform:
      | "behance"
      | "bluesky"
      | "ig"
      | "linkedin"
      | "linktree"
      | "mastodon"
      | "tiktok"
      | "x"
      | "website";
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type CountryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "country";
};

export type CityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "city";
};

export type Location = {
  _type: "location";
  country: CountryReference;
  city: CityReference;
};

export type TypeFoundry = {
  _id: string;
  _type: "typeFoundry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagSelector?: TagSelector;
  location: Location;
  socialLinks?: SocialLinks;
};

export type PublishingDate = {
  _type: "publishingDate";
  date: string;
};

export type InstituteReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "institute";
};

export type StudioReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "studio";
};

export type Professional = {
  _id: string;
  _type: "professional";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  portrait?: ImageWithMetadata;
  birthYear?: number;
  bio?: string;
  teachingAt?: InstituteReference;
  studio?: StudioReference;
  location?: Location;
  socialLinks?: SocialLinks;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  homeIntro: string;
  projectsIntro: string;
  interviewsIntro: string;
  designersIntro: string;
  projectsPage?: {
    seo?: SeoModule;
  };
  blogPage?: {
    seo?: SeoModule;
  };
};

export type SeoModule = {
  _type: "seoModule";
  metaTitle: string;
  metaDescription: string;
  metaRobots?:
    | "index, follow"
    | "noindex, follow"
    | "index, nofollow"
    | "noindex, nofollow";
  canonicalURL?: string;
  openGraph?: OpenGraph;
  xCard?: XCard;
  metaImage?: ImageWithMetadata;
};

export type XCard = {
  _type: "xCard";
  cardType?: "summary" | "summary_large_image";
  title?: string;
  description?: string;
  image?: ImageWithMetadata;
};

export type OpenGraph = {
  _type: "openGraph";
  title?: string;
  description?: string;
  image?: ImageWithMetadata;
  url?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Country = {
  _id: string;
  _type: "country";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type City = {
  _id: string;
  _type: "city";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type TitleSlug = {
  _type: "titleSlug";
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Logo = {
  _type: "logo";
  logoLight?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type Studio = {
  _id: string;
  _type: "studio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  category: CategoryReference;
  tagSelector?: TagSelector;
  locations?: Array<
    {
      _key: string;
    } & Location
  >;
  socialLinks?: SocialLinks;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type DesignerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "designer";
};

export type TeacherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teacher";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishingDate?: PublishingDate;
  designer: DesignerReference;
  cover: ImageWithMetadata;
  institute?: InstituteReference;
  teacher?: TeacherReference;
  year: number;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  gallery?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  description?: string;
  seo?: SeoModule;
};

export type Teacher = {
  _id: string;
  _type: "teacher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  teachingAt?: InstituteReference;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Interview = {
  _id: string;
  _type: "interview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishingDate?: PublishingDate;
  cover: ImageWithMetadata;
  interviewTo: Array<
    {
      _key: string;
    } & DesignerReference
  >;
  introText: string;
  interview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type ContributorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contributor";
};

export type History = {
  _id: string;
  _type: "history";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  supporters?: ContributorReference;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type: string;
  cover: ImageWithMetadata;
  dateStart: string;
  dateEnd?: string;
  locationName?: string;
  locationAddress?: string;
  description?: string;
  sponsor?: ContributorReference;
  partner?: ContributorReference;
};

export type Edition = {
  _id: string;
  _type: "edition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  cover: ImageWithMetadata;
};

export type Designer = {
  _id: string;
  _type: "designer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  portrait?: ImageWithMetadata;
  birthYear: number;
  bio?: string;
  education?: Array<{
    institute: InstituteReference;
    degree: "Bachelor" | "Master" | "PhD" | "Other";
    year?: number;
    _type: "instituteEducation";
    _key: string;
  }>;
  location: Location;
  socialLinks?: SocialLinks;
};

export type Institute = {
  _id: string;
  _type: "institute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  yearFoundation: number;
  languages?: Array<
    {
      _key: string;
    } & LanguageReference
  >;
  location: Location;
  address?: string;
  socialLinks?: SocialLinks;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Contributor = {
  _id: string;
  _type: "contributor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: Logo;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LanguageReference
  | AuthorReference
  | PublisherReference
  | Bibliography
  | TagReference
  | TagSelector
  | SanityImageAssetReference
  | ImageWithMetadata
  | CategoryReference
  | WebSource
  | Publisher
  | Author
  | Glossary
  | Bookshop
  | SocialLinks
  | CountryReference
  | CityReference
  | Location
  | TypeFoundry
  | PublishingDate
  | InstituteReference
  | StudioReference
  | Professional
  | SiteSettings
  | SeoModule
  | XCard
  | OpenGraph
  | Tag
  | Country
  | City
  | TitleSlug
  | Slug
  | Logo
  | Studio
  | Category
  | DesignerReference
  | TeacherReference
  | Project
  | Teacher
  | Language
  | Interview
  | ContributorReference
  | History
  | Event
  | Edition
  | Designer
  | Institute
  | SanityImageCrop
  | SanityImageHotspot
  | Contributor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    homeIntro,    projectsIntro,    interviewsIntro,    designersIntro,  }
export type SITE_SETTINGS_QUERY_RESULT = {
  homeIntro: string;
  projectsIntro: string;
  interviewsIntro: string;
  designersIntro: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc) {    _id,    cover {      image {        asset,        alt,        hotspot,        crop      }    },    title,    slug,    designer->{      _id,      name,      slug,      portrait    },    tags[]->{      _id,      name,      slug    },    seo {      metaTitle,      metaDescription,      metaRobots,      canonicalPath,      openGraph {        title,        description,        image,        url      },      xCard {        cardType,        title,        description,        image      },      metaImage    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  cover: {
    image: {
      asset: SanityImageAssetReference | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  title: string;
  slug: Slug;
  designer: {
    _id: string;
    name: string;
    slug: null;
    portrait: ImageWithMetadata | null;
  };
  tags: Array<{
    _id: string;
    name: string;
    slug: null;
  }> | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalPath: null;
    openGraph: {
      title: string | null;
      description: string | null;
      image: ImageWithMetadata | null;
      url: string | null;
    } | null;
    xCard: {
      cardType: "summary_large_image" | "summary" | null;
      title: string | null;
      description: string | null;
      image: ImageWithMetadata | null;
    } | null;
    metaImage: ImageWithMetadata | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    cover {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt    },    title,    slug,    designer->{      _id,      name,      slug,      portrait    },    tags[]->{      _id,      name,      slug    },    teacher->{      _id,      name,    },    institute->{      _id,      name,    },    year,    gallery,    description,    seo {      metaTitle,      metaDescription,      metaRobots,      canonicalPath,      openGraph {        title,        description,        image,        url      },      xCard {        cardType,        title,        description,        image      },      metaImage    }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  cover: {
    _type: "imageWithMetadata";
    image: {
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  };
  title: string;
  slug: Slug;
  designer: {
    _id: string;
    name: string;
    slug: null;
    portrait: ImageWithMetadata | null;
  };
  tags: Array<{
    _id: string;
    name: string;
    slug: null;
  }> | null;
  teacher: {
    _id: string;
    name: string;
  } | null;
  institute: {
    _id: string;
    name: string;
  } | null;
  year: number;
  gallery: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  description: string | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalPath: null;
    openGraph: {
      title: string | null;
      description: string | null;
      image: ImageWithMetadata | null;
      url: string | null;
    } | null;
    xCard: {
      cardType: "summary_large_image" | "summary" | null;
      title: string | null;
      description: string | null;
      image: ImageWithMetadata | null;
    } | null;
    metaImage: ImageWithMetadata | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    homeIntro,\n    projectsIntro,\n    interviewsIntro,\n    designersIntro,\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "project"] | order(_createdAt desc) {\n    _id,\n    cover {\n      image {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    title,\n    slug,\n    designer->{\n      _id,\n      name,\n      slug,\n      portrait\n    },\n    tags[]->{\n      _id,\n      name,\n      slug\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      metaRobots,\n      canonicalPath,\n      openGraph {\n        title,\n        description,\n        image,\n        url\n      },\n      xCard {\n        cardType,\n        title,\n        description,\n        image\n      },\n      metaImage\n    }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    cover {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt\n    },\n    title,\n    slug,\n    designer->{\n      _id,\n      name,\n      slug,\n      portrait\n    },\n    tags[]->{\n      _id,\n      name,\n      slug\n    },\n    teacher->{\n      _id,\n      name,\n    },\n    institute->{\n      _id,\n      name,\n    },\n    year,\n    gallery,\n    description,\n    seo {\n      metaTitle,\n      metaDescription,\n      metaRobots,\n      canonicalPath,\n      openGraph {\n        title,\n        description,\n        image,\n        url\n      },\n      xCard {\n        cardType,\n        title,\n        description,\n        image\n      },\n      metaImage\n    }\n  }\n': PROJECT_QUERY_RESULT;
  }
}
