/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: src/sanity/extract.json
export type LanguageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "language";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type PublisherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publisher";
};

export type Bibliography = {
  _id: string;
  _type: "bibliography";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  isbn?: string;
  name: string;
  cover?: ImageWithMetadata;
  year?: number;
  description?: string;
  pageCount?: number;
  languages?: Array<
    {
      _key: string;
    } & LanguageReference
  >;
  fetchedLanguages?: string;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  fetchedAuthors?: string;
  publisher: PublisherReference;
  fetchedPublisher?: string;
  tagSelector?: TagSelector;
  fetchedCategories?: string;
  affiliateLink?: string;
  categories?: Array<string>;
  googleBooksId?: string;
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type TagSelector = {
  _type: "tagSelector";
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithMetadata = {
  _type: "imageWithMetadata";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  alt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type WebSource = {
  _id: string;
  _type: "webSource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sourceUrl: string;
  name: string;
  description?: string;
  cover?: ImageWithMetadata;
  category: CategoryReference;
  tagSelector?: TagSelector;
  ogTitle?: string;
  ogDescription?: string;
  ogSiteName?: string;
  ogImageUrl?: string;
};

export type Publisher = {
  _id: string;
  _type: "publisher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Glossary = {
  _id: string;
  _type: "glossary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  description: string;
  image?: ImageWithMetadata;
  seo?: SeoModule;
};

export type SeoModule = {
  _type: "seoModule";
  metaTitle?: string;
  metaDescription?: string;
  metaImage?: ImageWithMetadata;
  metaRobots?:
    | "index, follow"
    | "noindex, follow"
    | "index, nofollow"
    | "noindex, nofollow";
  canonicalURL?: string;
  openGraph?: OpenGraph;
  xCard?: XCard;
};

export type Bookshop = {
  _id: string;
  _type: "bookshop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagSelector?: TagSelector;
  location: Location;
  address?: string;
  socialLinks?: SocialLinks;
};

export type SocialLinks = {
  _type: "socialLinks";
  links?: Array<{
    platform:
      | "behance"
      | "bluesky"
      | "ig"
      | "linkedin"
      | "linktree"
      | "mastodon"
      | "spotify"
      | "substack"
      | "tiktok"
      | "x"
      | "website";
    url: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type CountryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "country";
};

export type CityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "city";
};

export type Location = {
  _type: "location";
  country: CountryReference;
  city: CityReference;
};

export type TypeFoundry = {
  _id: string;
  _type: "typeFoundry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagSelector?: TagSelector;
  location: Location;
  socialLinks?: SocialLinks;
};

export type PublishingDate = {
  _type: "publishingDate";
  date: string;
};

export type InstituteReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "institute";
};

export type StudioReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "studio";
};

export type Professional = {
  _id: string;
  _type: "professional";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  portrait?: ImageWithMetadata;
  birthYear?: number;
  bio?: string;
  teachingAt?: InstituteReference;
  studio?: StudioReference;
  location?: Location;
  socialLinks?: SocialLinks;
};

export type CtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cta";
};

export type EventsPage = {
  _id: string;
  _type: "eventsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText: string;
  endOfPageCta?: CtaReference;
  seo?: SeoModule;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  seo?: SeoModule;
  substackUrl?: string;
  instagramUrl?: string;
  spotifyUrl?: string;
  utmSource: string;
  utmMedium?: string;
  utmCampaign?: string;
};

export type XCard = {
  _type: "xCard";
  title?: string;
  description?: string;
};

export type OpenGraph = {
  _type: "openGraph";
  title?: string;
  description?: string;
  url?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type TitleSlug = {
  _type: "titleSlug";
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type GridFourMediaBlock = {
  _type: "gridFourMediaBlock";
  topLeft: MediaItem;
  topRight: MediaItem;
  bottomLeft: MediaItem;
  bottomRight: MediaItem;
};

export type ThreeSideBySideMediaBlock = {
  _type: "threeSideBySideMediaBlock";
  left: MediaItem;
  center: MediaItem;
  right: MediaItem;
};

export type SideBySideMediaBlock = {
  _type: "sideBySideMediaBlock";
  left: MediaItem;
  right: MediaItem;
};

export type SingleMediaBlock = {
  _type: "singleMediaBlock";
  media: MediaItem;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MediaItem = {
  _type: "mediaItem";
  type: "image" | "videoUpload" | "videoEmbed";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  videoUrl?: string;
  caption?: string;
  alt?: string;
};

export type Logo = {
  _type: "logo";
  logoLight?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type Teacher = {
  _id: string;
  _type: "teacher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  teachingAt?: InstituteReference;
};

export type Language = {
  _id: string;
  _type: "language";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type ContributorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contributor";
};

export type History = {
  _id: string;
  _type: "history";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  supporters?: ContributorReference;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type InterviewReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "interview";
};

export type JournalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "journal";
};

export type DesignerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "designer";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type EditionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "edition";
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type ProjectsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectsPage";
};

export type InterviewsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "interviewsPage";
};

export type DesignersPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "designersPage";
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  variant?: "simple" | "withImage";
  headline?: string;
  image?: ImageWithMetadata;
  buttonText: string;
  linkType?: "internal" | "external";
  internalLink?:
    | ProjectReference
    | InterviewReference
    | JournalReference
    | DesignerReference
    | EventReference
    | EditionReference
    | HomePageReference
    | ProjectsPageReference
    | InterviewsPageReference
    | DesignersPageReference;
  externalUrl?: string;
};

export type DesignersPage = {
  _id: string;
  _type: "designersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText: string;
  endOfPageCta?: CtaReference;
  seo?: SeoModule;
};

export type InterviewsPage = {
  _id: string;
  _type: "interviewsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText: string;
  endOfPageCta?: CtaReference;
  seo?: SeoModule;
};

export type ProjectsPage = {
  _id: string;
  _type: "projectsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText: string;
  endOfPageCta?: CtaReference;
  seo?: SeoModule;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText: string;
  endOfPageCta?: CtaReference;
  seo?: SeoModule;
};

export type Edition = {
  _id: string;
  _type: "edition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  cover: ImageWithMetadata;
  seo?: SeoModule;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type: string;
  cover: ImageWithMetadata;
  dateStart: string;
  dateEnd?: string;
  locationName?: string;
  locationAddress?: string;
  description?: string;
  sponsor?: ContributorReference;
  partner?: ContributorReference;
};

export type Designer = {
  _id: string;
  _type: "designer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  portrait?: ImageWithMetadata;
  birthYear: number;
  bio?: string;
  education?: Array<{
    institute: InstituteReference;
    degree: "Bachelor" | "Master" | "PhD" | "Other";
    year?: number;
    _type: "instituteEducation";
    _key: string;
  }>;
  location: Location;
  socialLinks?: SocialLinks;
  seo?: SeoModule;
};

export type Journal = {
  _id: string;
  _type: "journal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishingDate?: PublishingDate;
  cover: ImageWithMetadata;
  authors?: Array<
    {
      _key: string;
    } & AuthorReference
  >;
  excerpt?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  seo?: SeoModule;
};

export type ProfessionalReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "professional";
};

export type Interview = {
  _id: string;
  _type: "interview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishingDate?: PublishingDate;
  cover: ImageWithMetadata;
  interviewToType: "designers" | "studio";
  designersAndProfessionals?: ArrayOf<
    DesignerReference | ProfessionalReference
  >;
  studio?: StudioReference;
  city?: CityReference;
  country?: CountryReference;
  readingTime?: number;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  introText: string;
  interview?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "answer" | "blockquote";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & SingleMediaBlock)
    | ({
        _key: string;
      } & SideBySideMediaBlock)
    | ({
        _key: string;
      } & ThreeSideBySideMediaBlock)
    | ({
        _key: string;
      } & GridFourMediaBlock)
  >;
  seo?: SeoModule;
};

export type Country = {
  _id: string;
  _type: "country";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type City = {
  _id: string;
  _type: "city";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type Studio = {
  _id: string;
  _type: "studio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  category: CategoryReference;
  tagSelector?: TagSelector;
  locations?: Array<
    {
      _key: string;
    } & Location
  >;
  socialLinks?: SocialLinks;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
};

export type TeacherReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teacher";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishingDate: PublishingDate;
  cover: ImageWithMetadata;
  designers: Array<
    {
      _key: string;
    } & DesignerReference
  >;
  institute?: InstituteReference;
  teachers?: Array<
    {
      _key: string;
    } & TeacherReference
  >;
  year: number;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  description?: string;
  gallery?: Array<
    | ({
        _key: string;
      } & SingleMediaBlock)
    | ({
        _key: string;
      } & SideBySideMediaBlock)
  >;
  seo?: SeoModule;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Institute = {
  _id: string;
  _type: "institute";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  yearFoundation: number;
  languages?: Array<
    {
      _key: string;
    } & LanguageReference
  >;
  location: Location;
  address?: string;
  socialLinks?: SocialLinks;
};

export type Contributor = {
  _id: string;
  _type: "contributor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo: Logo;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LanguageReference
  | AuthorReference
  | PublisherReference
  | Bibliography
  | TagReference
  | TagSelector
  | SanityImageAssetReference
  | ImageWithMetadata
  | CategoryReference
  | WebSource
  | Publisher
  | Author
  | Glossary
  | SeoModule
  | Bookshop
  | SocialLinks
  | CountryReference
  | CityReference
  | Location
  | TypeFoundry
  | PublishingDate
  | InstituteReference
  | StudioReference
  | Professional
  | CtaReference
  | EventsPage
  | SiteSettings
  | XCard
  | OpenGraph
  | Tag
  | TitleSlug
  | Slug
  | GridFourMediaBlock
  | ThreeSideBySideMediaBlock
  | SideBySideMediaBlock
  | SingleMediaBlock
  | SanityFileAssetReference
  | MediaItem
  | Logo
  | Teacher
  | Language
  | ContributorReference
  | History
  | ProjectReference
  | InterviewReference
  | JournalReference
  | DesignerReference
  | EventReference
  | EditionReference
  | HomePageReference
  | ProjectsPageReference
  | InterviewsPageReference
  | DesignersPageReference
  | Cta
  | DesignersPage
  | InterviewsPage
  | ProjectsPage
  | HomePage
  | Edition
  | Event
  | Designer
  | Journal
  | ProfessionalReference
  | Interview
  | Country
  | City
  | Studio
  | Category
  | TeacherReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Institute
  | Contributor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    utmSource,    utmMedium,    utmCampaign,    substackUrl,    instagramUrl,    spotifyUrl  }
export type SITE_SETTINGS_QUERY_RESULT = {
  utmSource: string;
  utmMedium: string | null;
  utmCampaign: string | null;
  substackUrl: string | null;
  instagramUrl: string | null;
  spotifyUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0] {    _id,    title,    introText,      endOfPageCta->{    _id,    title,    variant,    headline,    image,    buttonText,    linkType,    internalLink->{      _type,      "slug": slug    },    externalUrl  },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type HOME_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  introText: string;
  endOfPageCta: {
    _id: string;
    title: string;
    variant: "simple" | "withImage" | null;
    headline: string | null;
    image: ImageWithMetadata | null;
    buttonText: string;
    linkType: "external" | "internal" | null;
    internalLink:
      | {
          _type: "designer";
          slug: Slug;
        }
      | {
          _type: "designersPage";
          slug: null;
        }
      | {
          _type: "edition";
          slug: Slug;
        }
      | {
          _type: "event";
          slug: Slug;
        }
      | {
          _type: "homePage";
          slug: null;
        }
      | {
          _type: "interview";
          slug: Slug;
        }
      | {
          _type: "interviewsPage";
          slug: null;
        }
      | {
          _type: "journal";
          slug: Slug;
        }
      | {
          _type: "project";
          slug: Slug;
        }
      | {
          _type: "projectsPage";
          slug: null;
        }
      | null;
    externalUrl: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_PAGE_QUERY
// Query: *[_type == "projectsPage"][0] {    _id,    title,    introText,      endOfPageCta->{    _id,    title,    variant,    headline,    image,    buttonText,    linkType,    internalLink->{      _type,      "slug": slug    },    externalUrl  },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type PROJECTS_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  introText: string;
  endOfPageCta: {
    _id: string;
    title: string;
    variant: "simple" | "withImage" | null;
    headline: string | null;
    image: ImageWithMetadata | null;
    buttonText: string;
    linkType: "external" | "internal" | null;
    internalLink:
      | {
          _type: "designer";
          slug: Slug;
        }
      | {
          _type: "designersPage";
          slug: null;
        }
      | {
          _type: "edition";
          slug: Slug;
        }
      | {
          _type: "event";
          slug: Slug;
        }
      | {
          _type: "homePage";
          slug: null;
        }
      | {
          _type: "interview";
          slug: Slug;
        }
      | {
          _type: "interviewsPage";
          slug: null;
        }
      | {
          _type: "journal";
          slug: Slug;
        }
      | {
          _type: "project";
          slug: Slug;
        }
      | {
          _type: "projectsPage";
          slug: null;
        }
      | null;
    externalUrl: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: INTERVIEWS_PAGE_QUERY
// Query: *[_type == "interviewsPage"][0] {    _id,    title,    introText,      endOfPageCta->{    _id,    title,    variant,    headline,    image,    buttonText,    linkType,    internalLink->{      _type,      "slug": slug    },    externalUrl  },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type INTERVIEWS_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  introText: string;
  endOfPageCta: {
    _id: string;
    title: string;
    variant: "simple" | "withImage" | null;
    headline: string | null;
    image: ImageWithMetadata | null;
    buttonText: string;
    linkType: "external" | "internal" | null;
    internalLink:
      | {
          _type: "designer";
          slug: Slug;
        }
      | {
          _type: "designersPage";
          slug: null;
        }
      | {
          _type: "edition";
          slug: Slug;
        }
      | {
          _type: "event";
          slug: Slug;
        }
      | {
          _type: "homePage";
          slug: null;
        }
      | {
          _type: "interview";
          slug: Slug;
        }
      | {
          _type: "interviewsPage";
          slug: null;
        }
      | {
          _type: "journal";
          slug: Slug;
        }
      | {
          _type: "project";
          slug: Slug;
        }
      | {
          _type: "projectsPage";
          slug: null;
        }
      | null;
    externalUrl: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: DESIGNERS_PAGE_QUERY
// Query: *[_type == "designersPage"][0] {    _id,    title,    introText,      endOfPageCta->{    _id,    title,    variant,    headline,    image,    buttonText,    linkType,    internalLink->{      _type,      "slug": slug    },    externalUrl  },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type DESIGNERS_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  introText: string;
  endOfPageCta: {
    _id: string;
    title: string;
    variant: "simple" | "withImage" | null;
    headline: string | null;
    image: ImageWithMetadata | null;
    buttonText: string;
    linkType: "external" | "internal" | null;
    internalLink:
      | {
          _type: "designer";
          slug: Slug;
        }
      | {
          _type: "designersPage";
          slug: null;
        }
      | {
          _type: "edition";
          slug: Slug;
        }
      | {
          _type: "event";
          slug: Slug;
        }
      | {
          _type: "homePage";
          slug: null;
        }
      | {
          _type: "interview";
          slug: Slug;
        }
      | {
          _type: "interviewsPage";
          slug: null;
        }
      | {
          _type: "journal";
          slug: Slug;
        }
      | {
          _type: "project";
          slug: Slug;
        }
      | {
          _type: "projectsPage";
          slug: null;
        }
      | null;
    externalUrl: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EVENTS_PAGE_QUERY
// Query: *[_type == "eventsPage"][0] {    _id,    title,    introText,      endOfPageCta->{    _id,    title,    variant,    headline,    image,    buttonText,    linkType,    internalLink->{      _type,      "slug": slug    },    externalUrl  },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type EVENTS_PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  introText: string;
  endOfPageCta: {
    _id: string;
    title: string;
    variant: "simple" | "withImage" | null;
    headline: string | null;
    image: ImageWithMetadata | null;
    buttonText: string;
    linkType: "external" | "internal" | null;
    internalLink:
      | {
          _type: "designer";
          slug: Slug;
        }
      | {
          _type: "designersPage";
          slug: null;
        }
      | {
          _type: "edition";
          slug: Slug;
        }
      | {
          _type: "event";
          slug: Slug;
        }
      | {
          _type: "homePage";
          slug: null;
        }
      | {
          _type: "interview";
          slug: Slug;
        }
      | {
          _type: "interviewsPage";
          slug: null;
        }
      | {
          _type: "journal";
          slug: Slug;
        }
      | {
          _type: "project";
          slug: Slug;
        }
      | {
          _type: "projectsPage";
          slug: null;
        }
      | null;
    externalUrl: string | null;
  } | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(_createdAt desc) {    _id,    cover {      image {        asset,        alt,        hotspot,        crop      }    },    title,    slug,    designers[]{ _key, ...@->{ _id, name, slug, portrait } },    tags[]{ _key, ...@->{ _id, name, slug } },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  cover: {
    image: {
      asset: SanityImageAssetReference | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  title: string;
  slug: Slug;
  designers: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: Slug;
    portrait: ImageWithMetadata | null;
  }>;
  tags: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    cover {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt    },    title,    slug,    designers[]{ _key, ...@->{ _id, name, slug, portrait } },    tags[]{ _key, ...@->{ _id, name, slug } },    teachers[]{ _key, ...@->{ _id, name } },    institute->{      _id,      name,    },    year,    gallery,    description,      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  cover: {
    _type: "imageWithMetadata";
    image: {
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  };
  title: string;
  slug: Slug;
  designers: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: Slug;
    portrait: ImageWithMetadata | null;
  }>;
  tags: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: null;
  }> | null;
  teachers: Array<{
    _key: string;
    _id: string;
    name: string;
  }> | null;
  institute: {
    _id: string;
    name: string;
  } | null;
  year: number;
  gallery: Array<
    | ({
        _key: string;
      } & SideBySideMediaBlock)
    | ({
        _key: string;
      } & SingleMediaBlock)
  > | null;
  description: string | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: INTERVIEWS_QUERY
// Query: *[_type == "interview"] | order(publishingDate.date desc) {    _id,    title,    slug,    publishingDate,    cover {      image {        asset,        alt,        hotspot,        crop      }    },    designers[]{ _key, ...@->{ _id, name } },    studio->{      _id,      name    },    city->{      _id,      name    },    country->{      _id,      name    },    readingTime,    tags[]{ _key, ...@->{ _id, name, slug } },    introText,      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type INTERVIEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  publishingDate: PublishingDate | null;
  cover: {
    image: {
      asset: SanityImageAssetReference | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
  };
  designers: null;
  studio: {
    _id: string;
    name: string;
  } | null;
  city: {
    _id: string;
    name: string;
  } | null;
  country: {
    _id: string;
    name: string;
  } | null;
  readingTime: number | null;
  tags: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: null;
  }> | null;
  introText: string;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: INTERVIEW_QUERY
// Query: *[_type == "interview" && slug.current == $slug][0] {    _id,    title,    slug,    publishingDate,    cover {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt    },    designers[]{ _key, ...@->{ _id, name, portrait } },    studio->{      _id,      name    },    city->{      _id,      name    },    country->{      _id,      name    },    readingTime,    tags[]{ _key, ...@->{ _id, name, slug } },    introText,    interview[] {      ...,      _type == "imageBlock" => {        _key,        _type,        image {          image {            asset,            hotspot,            crop          },          alt,          caption        }      },      _type == "multipleImageBlock" => {        _key,        _type,        images[] {          _key,          image {            asset,            hotspot,            crop          },          alt,          caption        }      }    },      seo {    metaTitle,    metaDescription,    metaRobots,    canonicalURL,    openGraph {      title,      description,      url    },    xCard {      title,      description    },    metaImage {      _type,      image {        _type,        asset,        hotspot,        crop      },      alt,      caption    }  }  }
export type INTERVIEW_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  publishingDate: PublishingDate | null;
  cover: {
    _type: "imageWithMetadata";
    image: {
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  };
  designers: null;
  studio: {
    _id: string;
    name: string;
  } | null;
  city: {
    _id: string;
    name: string;
  } | null;
  country: {
    _id: string;
    name: string;
  } | null;
  readingTime: number | null;
  tags: Array<{
    _key: string;
    _id: string;
    name: string;
    slug: null;
  }> | null;
  introText: string;
  interview: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "answer" | "blockquote" | "normal";
        listItem?: never;
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "gridFourMediaBlock";
        topLeft: MediaItem;
        topRight: MediaItem;
        bottomLeft: MediaItem;
        bottomRight: MediaItem;
      }
    | {
        _key: string;
        _type: "sideBySideMediaBlock";
        left: MediaItem;
        right: MediaItem;
      }
    | {
        _key: string;
        _type: "singleMediaBlock";
        media: MediaItem;
      }
    | {
        _key: string;
        _type: "threeSideBySideMediaBlock";
        left: MediaItem;
        center: MediaItem;
        right: MediaItem;
      }
  > | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    metaRobots:
      | "index, follow"
      | "index, nofollow"
      | "noindex, follow"
      | "noindex, nofollow"
      | null;
    canonicalURL: string | null;
    openGraph: {
      title: string | null;
      description: string | null;
      url: string | null;
    } | null;
    xCard: {
      title: string | null;
      description: string | null;
    } | null;
    metaImage: {
      _type: "imageWithMetadata";
      image: {
        _type: "image";
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      alt: string | null;
      caption: string | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BIBLIOGRAPHY_QUERY
// Query: *[_type == "bibliography"] | order(name asc) {    _id,    name,    year,    cover {      image { asset, hotspot, crop },      alt    },    languages[]{ _key, ...@->{ _id, name } },    authors[]{ _key, ...@->{ _id, name } },    publisher->{      _id,      name    },    tagSelector {      tags[]->{        _id,        name      }    },    affiliateLink,    isbn,    description,    pageCount,    categories  }
export type BIBLIOGRAPHY_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  year: number | null;
  cover: {
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  } | null;
  languages: Array<{
    _key: string;
    _id: string;
    name: string;
  }> | null;
  authors: Array<{
    _key: string;
    _id: string;
    name: string;
  }> | null;
  publisher: {
    _id: string;
    name: string;
  };
  tagSelector: {
    tags: Array<{
      _id: string;
      name: string;
    }> | null;
  } | null;
  affiliateLink: string | null;
  isbn: string | null;
  description: string | null;
  pageCount: number | null;
  categories: Array<string> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BOOKSHOPS_QUERY
// Query: *[_type == "bookshop"] | order(name asc) {    _id,    name,    tagSelector {      tags[]->{        _id,        name      }    },    location {      country->{        _id,        name      },      city->{        _id,        name      }    },    address,    socialLinks {      links[] {        _key,        platform,        url      }    }  }
export type BOOKSHOPS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  tagSelector: {
    tags: Array<{
      _id: string;
      name: string;
    }> | null;
  } | null;
  location: {
    country: {
      _id: string;
      name: string;
    };
    city: {
      _id: string;
      name: string;
    };
  };
  address: string | null;
  socialLinks: {
    links: Array<{
      _key: string;
      platform:
        | "behance"
        | "bluesky"
        | "ig"
        | "linkedin"
        | "linktree"
        | "mastodon"
        | "spotify"
        | "substack"
        | "tiktok"
        | "website"
        | "x";
      url: string;
    }> | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: GLOSSARY_QUERY
// Query: *[_type == "glossary"] | order(name asc) {    _id,    name,    description,    image {      image { asset, hotspot, crop },      alt    }  }
export type GLOSSARY_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  description: string;
  image: {
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: INSTITUTES_QUERY
// Query: *[_type == "institute"] | order(name asc) {    _id,    name,    yearFoundation,    languages[]->{      _id,      name    },    location {      country->{        _id,        name      },      city->{        _id,        name      }    },    address,    socialLinks {      links[] {        _key,        platform,        url      }    }  }
export type INSTITUTES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  yearFoundation: number;
  languages: Array<{
    _id: string;
    name: string;
  }> | null;
  location: {
    country: {
      _id: string;
      name: string;
    };
    city: {
      _id: string;
      name: string;
    };
  };
  address: string | null;
  socialLinks: {
    links: Array<{
      _key: string;
      platform:
        | "behance"
        | "bluesky"
        | "ig"
        | "linkedin"
        | "linktree"
        | "mastodon"
        | "spotify"
        | "substack"
        | "tiktok"
        | "website"
        | "x";
      url: string;
    }> | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: STUDIOS_QUERY
// Query: *[_type == "studio"] | order(name asc) {    _id,    name,    category->{      _id,      name    },    tagSelector {      tags[]->{        _id,        name      }    },    locations[] {      _key,      country->{        _id,        name      },      city->{        _id,        name      }    },    socialLinks {      links[] {        _key,        platform,        url      }    }  }
export type STUDIOS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  category: {
    _id: string;
    name: string;
  };
  tagSelector: {
    tags: Array<{
      _id: string;
      name: string;
    }> | null;
  } | null;
  locations: Array<{
    _key: string;
    country: {
      _id: string;
      name: string;
    };
    city: {
      _id: string;
      name: string;
    };
  }> | null;
  socialLinks: {
    links: Array<{
      _key: string;
      platform:
        | "behance"
        | "bluesky"
        | "ig"
        | "linkedin"
        | "linktree"
        | "mastodon"
        | "spotify"
        | "substack"
        | "tiktok"
        | "website"
        | "x";
      url: string;
    }> | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TYPE_FOUNDRIES_QUERY
// Query: *[_type == "typeFoundry"] | order(name asc) {    _id,    name,    tagSelector {      tags[]->{        _id,        name      }    },    location {      country->{        _id,        name      },      city->{        _id,        name      }    },    socialLinks {      links[] {        _key,        platform,        url      }    }  }
export type TYPE_FOUNDRIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  tagSelector: {
    tags: Array<{
      _id: string;
      name: string;
    }> | null;
  } | null;
  location: {
    country: {
      _id: string;
      name: string;
    };
    city: {
      _id: string;
      name: string;
    };
  };
  socialLinks: {
    links: Array<{
      _key: string;
      platform:
        | "behance"
        | "bluesky"
        | "ig"
        | "linkedin"
        | "linktree"
        | "mastodon"
        | "spotify"
        | "substack"
        | "tiktok"
        | "website"
        | "x";
      url: string;
    }> | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: WEB_SOURCES_QUERY
// Query: *[_type == "webSource"] | order(name asc) {    _id,    name,    description,    cover {      image { asset, hotspot, crop },      alt    },    category->{      _id,      name    },    tagSelector {      tags[]{ _key, ...@->{ _id, name } }    },    sourceUrl,    ogTitle,    ogDescription,    ogSiteName,    ogImageUrl  }
export type WEB_SOURCES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  description: string | null;
  cover: {
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    _id: string;
    name: string;
  };
  tagSelector: {
    tags: Array<{
      _key: string;
      _id: string;
      name: string;
    }> | null;
  } | null;
  sourceUrl: string;
  ogTitle: string | null;
  ogDescription: string | null;
  ogSiteName: string | null;
  ogImageUrl: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    utmSource,\n    utmMedium,\n    utmCampaign,\n    substackUrl,\n    instagramUrl,\n    spotifyUrl\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0] {\n    _id,\n    title,\n    introText,\n    \n  endOfPageCta->{\n    _id,\n    title,\n    variant,\n    headline,\n    image,\n    buttonText,\n    linkType,\n    internalLink->{\n      _type,\n      "slug": slug\n    },\n    externalUrl\n  }\n,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "projectsPage"][0] {\n    _id,\n    title,\n    introText,\n    \n  endOfPageCta->{\n    _id,\n    title,\n    variant,\n    headline,\n    image,\n    buttonText,\n    linkType,\n    internalLink->{\n      _type,\n      "slug": slug\n    },\n    externalUrl\n  }\n,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': PROJECTS_PAGE_QUERY_RESULT;
    '\n  *[_type == "interviewsPage"][0] {\n    _id,\n    title,\n    introText,\n    \n  endOfPageCta->{\n    _id,\n    title,\n    variant,\n    headline,\n    image,\n    buttonText,\n    linkType,\n    internalLink->{\n      _type,\n      "slug": slug\n    },\n    externalUrl\n  }\n,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': INTERVIEWS_PAGE_QUERY_RESULT;
    '\n  *[_type == "designersPage"][0] {\n    _id,\n    title,\n    introText,\n    \n  endOfPageCta->{\n    _id,\n    title,\n    variant,\n    headline,\n    image,\n    buttonText,\n    linkType,\n    internalLink->{\n      _type,\n      "slug": slug\n    },\n    externalUrl\n  }\n,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': DESIGNERS_PAGE_QUERY_RESULT;
    '\n  *[_type == "eventsPage"][0] {\n    _id,\n    title,\n    introText,\n    \n  endOfPageCta->{\n    _id,\n    title,\n    variant,\n    headline,\n    image,\n    buttonText,\n    linkType,\n    internalLink->{\n      _type,\n      "slug": slug\n    },\n    externalUrl\n  }\n,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': EVENTS_PAGE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(_createdAt desc) {\n    _id,\n    cover {\n      image {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    title,\n    slug,\n    designers[]{ _key, ...@->{ _id, name, slug, portrait } },\n    tags[]{ _key, ...@->{ _id, name, slug } },\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    cover {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt\n    },\n    title,\n    slug,\n    designers[]{ _key, ...@->{ _id, name, slug, portrait } },\n    tags[]{ _key, ...@->{ _id, name, slug } },\n    teachers[]{ _key, ...@->{ _id, name } },\n    institute->{\n      _id,\n      name,\n    },\n    year,\n    gallery,\n    description,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "interview"] | order(publishingDate.date desc) {\n    _id,\n    title,\n    slug,\n    publishingDate,\n    cover {\n      image {\n        asset,\n        alt,\n        hotspot,\n        crop\n      }\n    },\n    designers[]{ _key, ...@->{ _id, name } },\n    studio->{\n      _id,\n      name\n    },\n    city->{\n      _id,\n      name\n    },\n    country->{\n      _id,\n      name\n    },\n    readingTime,\n    tags[]{ _key, ...@->{ _id, name, slug } },\n    introText,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': INTERVIEWS_QUERY_RESULT;
    '\n  *[_type == "interview" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    publishingDate,\n    cover {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt\n    },\n    designers[]{ _key, ...@->{ _id, name, portrait } },\n    studio->{\n      _id,\n      name\n    },\n    city->{\n      _id,\n      name\n    },\n    country->{\n      _id,\n      name\n    },\n    readingTime,\n    tags[]{ _key, ...@->{ _id, name, slug } },\n    introText,\n    interview[] {\n      ...,\n      _type == "imageBlock" => {\n        _key,\n        _type,\n        image {\n          image {\n            asset,\n            hotspot,\n            crop\n          },\n          alt,\n          caption\n        }\n      },\n      _type == "multipleImageBlock" => {\n        _key,\n        _type,\n        images[] {\n          _key,\n          image {\n            asset,\n            hotspot,\n            crop\n          },\n          alt,\n          caption\n        }\n      }\n    },\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaRobots,\n    canonicalURL,\n    openGraph {\n      title,\n      description,\n      url\n    },\n    xCard {\n      title,\n      description\n    },\n    metaImage {\n      _type,\n      image {\n        _type,\n        asset,\n        hotspot,\n        crop\n      },\n      alt,\n      caption\n    }\n  }\n\n  }\n': INTERVIEW_QUERY_RESULT;
    '\n  *[_type == "bibliography"] | order(name asc) {\n    _id,\n    name,\n    year,\n    cover {\n      image { asset, hotspot, crop },\n      alt\n    },\n    languages[]{ _key, ...@->{ _id, name } },\n    authors[]{ _key, ...@->{ _id, name } },\n    publisher->{\n      _id,\n      name\n    },\n    tagSelector {\n      tags[]->{\n        _id,\n        name\n      }\n    },\n    affiliateLink,\n    isbn,\n    description,\n    pageCount,\n    categories\n  }\n': BIBLIOGRAPHY_QUERY_RESULT;
    '\n  *[_type == "bookshop"] | order(name asc) {\n    _id,\n    name,\n    tagSelector {\n      tags[]->{\n        _id,\n        name\n      }\n    },\n    location {\n      country->{\n        _id,\n        name\n      },\n      city->{\n        _id,\n        name\n      }\n    },\n    address,\n    socialLinks {\n      links[] {\n        _key,\n        platform,\n        url\n      }\n    }\n  }\n': BOOKSHOPS_QUERY_RESULT;
    '\n  *[_type == "glossary"] | order(name asc) {\n    _id,\n    name,\n    description,\n    image {\n      image { asset, hotspot, crop },\n      alt\n    }\n  }\n': GLOSSARY_QUERY_RESULT;
    '\n  *[_type == "institute"] | order(name asc) {\n    _id,\n    name,\n    yearFoundation,\n    languages[]->{\n      _id,\n      name\n    },\n    location {\n      country->{\n        _id,\n        name\n      },\n      city->{\n        _id,\n        name\n      }\n    },\n    address,\n    socialLinks {\n      links[] {\n        _key,\n        platform,\n        url\n      }\n    }\n  }\n': INSTITUTES_QUERY_RESULT;
    '\n  *[_type == "studio"] | order(name asc) {\n    _id,\n    name,\n    category->{\n      _id,\n      name\n    },\n    tagSelector {\n      tags[]->{\n        _id,\n        name\n      }\n    },\n    locations[] {\n      _key,\n      country->{\n        _id,\n        name\n      },\n      city->{\n        _id,\n        name\n      }\n    },\n    socialLinks {\n      links[] {\n        _key,\n        platform,\n        url\n      }\n    }\n  }\n': STUDIOS_QUERY_RESULT;
    '\n  *[_type == "typeFoundry"] | order(name asc) {\n    _id,\n    name,\n    tagSelector {\n      tags[]->{\n        _id,\n        name\n      }\n    },\n    location {\n      country->{\n        _id,\n        name\n      },\n      city->{\n        _id,\n        name\n      }\n    },\n    socialLinks {\n      links[] {\n        _key,\n        platform,\n        url\n      }\n    }\n  }\n': TYPE_FOUNDRIES_QUERY_RESULT;
    '\n  *[_type == "webSource"] | order(name asc) {\n    _id,\n    name,\n    description,\n    cover {\n      image { asset, hotspot, crop },\n      alt\n    },\n    category->{\n      _id,\n      name\n    },\n    tagSelector {\n      tags[]{ _key, ...@->{ _id, name } }\n    },\n    sourceUrl,\n    ogTitle,\n    ogDescription,\n    ogSiteName,\n    ogImageUrl\n  }\n': WEB_SOURCES_QUERY_RESULT;
  }
}
